# Automatic labeling rules
# https://github.com/actions/labeler

"ci":
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**"

"dependencies":
  - changed-files:
    - any-glob-to-any-file:
      - "package.json"
      - "package-lock.json"
      - ".github/dependabot.yml"

"parser":
  - changed-files:
    - any-glob-to-any-file: "src/parser.ts"

"spec":
  - changed-files:
    - any-glob-to-any-file:
      - "src/validator.ts"
      - "src/context.ts"

"security":
  - changed-files:
    - any-glob-to-any-file:
      - "src/crypto.ts"
      - "src/global_config.ts"
      - "SECURITY.md"

"documentation":
  - changed-files:
    - any-glob-to-any-file:
      - "*.md"
      - "docs/**"
